afw/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('waldbestand/<int:inventory_pk>/', views.waldbestand, name='afw-bestand'),
    path('erschliessung/<int:inventory_pk>/', views.erschliessung, name='afw-erschliessung'),
]

ksp/urls.py
import sys

from django.conf import settings
from django.conf.urls import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.views import serve as static_serve
from django.urls import include, path

from observation import views
from mobile.views import (
    main as mobile_view, inventory_view, inventory_plots, map_redirect, sync_view
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('afw/', include('afw.urls')),

    path('mobile/', mobile_view),
    # Hooked at root level so as the scope can be for the whole project
    path('serviceworker.js', static_serve, kwargs={
        'path': 'js/serviceworker.js', 'insecure': True}),
    path('mobile/inventory/<int:pk>/geojson/', inventory_view, name="inventory-geojson"),
    path('mobile/inventory/<int:pk>/plots/', inventory_plots, name="inventory-plots"),
    path('mobile/plotobs/sync/', sync_view, name="plotobs-sync"),
    # Duplicate 'plotobs_detail_json' url for /mobile (cached) namespace
    path('mobile/plotobs/<int:pk>/json/', views.PlotObsDetailView.as_view(output='json'),
        name='mobile_plotobs_detail_json'),

    path('', views.GemeindenView.as_view(), name='home'),
    path('gemeinde/<int:pk>/', views.GemeindeDetailView.as_view(), name='gemeinde'),
    path('gemeinde/<int:pk>/plots/', views.GemeindePlotsView.as_view(), name='gemeinde-plots'),
    path('region/geojson/', views.AdminRegionGeoJson.as_view(), name='region-geojson'),
    path('inventory/<int:pk>/', views.InventoryView.as_view(), name='inventory'),
    path('inventory/<int:pk>/plotobs/', views.InventoryPlotObsView.as_view(),
        name='inventory-plotobs'),
    path('inventory/<int:pk>/plotsnoobs/', views.InventoryPlotNoObsView.as_view(),
        name='inventory-plots-no-obs'),
    path('inventory/<int:pk>/exclude_plots/', views.InventoryExcludePlotsView.as_view(),
        name='inventory-exclude-plots'),
    path('inventory/<int:pk>/plot/new/', views.InventoryAddPlotView.as_view(), name='inventory-new-plot'),
    path('inventory/<int:pk>/plot/fromshape/', views.InventoryPlotsFromShape.as_view(), name='inventory-new-plots-shape'),
    path('inventory/<int:pk>/savepolygon/', views.InventorySavePolygonView.as_view(), name='inventory-savepolygon'),
    # Views returning GeoJSON data
    path('plotobs/', views.PlotObsDataView.as_view(), name='plotobs'),
    path('plotobs/<int:pk>/json/', views.PlotObsDetailView.as_view(output='json'), name='plotobs_detail_json'),
    path('plotobs/<int:pk>/', views.PlotObsDetailView.as_view(output='html'), name='plotobs_detail'),
    path('plot/<int:pk>/', views.PlotDetailView.as_view(), name='plot_detail'),
    path('inventory/<int:pk>/plot/<int:plot_pk>/infos/', views.PlotDetailEmbedView.as_view(), name='plot_detail_embed'),
    path('waldbestand/<int:inventory_pk>/', views.waldbestand, name='obs-bestand'),
    # Temporary view:
    path('plot/tobechecked/', views.plots_to_check),
    path('tree/reconcile/', views.TreeReconcileView.as_view(), name='tree_reconcile'),
    path('tree/<int:pk>/edit/', views.TreeEditView.as_view(), name='tree_edit'),
    path('data/', views.DataPageView.as_view(), name='data_page'),
    path('data/grid/', views.DataGridView.as_view(), name='data_grid'),
    path('data/<str:model>/', views.ModelView.as_view(), name='data_model'),
    path('docs/', views.DocumentationView.as_view(), name='docs'),
    path('docs/glossar/', views.TemplateView.as_view(template_name='glossar.html'), name='glossar'),
    path('docs/<slug:slug>/', views.DocSpecificView.as_view(), name='doc-specific'),
    path('backups/<str:filename>/', views.serve_backup, name='serve-backup'),

    # Introspection views
    path('view_def/', views.ViewList.as_view(), name='view-list'),
    path('view_def/<int:oid>/', views.ViewDefinition.as_view(), name='view_def'),
    path('table_def/', views.TableListView.as_view(), name='table-list'),
    path('table_def/<str:oid_or_name>/', views.TableDefinitionView.as_view(), name='table_def'),
    path('func_def/<str:func_name>/', views.FunctionDefinitionView.as_view(), name='func_def'),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('chart/<str:view_name>/', views.chart, name="view_chart"),

]

if 'imports' in settings.INSTALLED_APPS:
    from imports import views as import_views
    urlpatterns += [
        path('import/form/', import_views.ImportView.as_view(), name="import"),
        path('import/', import_views.ImportedListView.as_view(), name="import_list"),
    ]

TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'

if settings.DEBUG or TESTING:
    # Serve media files in development
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Serve static mobile alias in developement
    urlpatterns += [
        path('mobile/static/<path:path>', static_serve),
    ]
    # Serve favicon in development
    urlpatterns.append(
        path('favicon.ico', static_serve, kwargs={'path': 'icons/favicon.ico'})
    )
if settings.REDIRECT_TILES:
    # Redirect map tiles in development
    urlpatterns.append(
        path('geowms.bl.ch/<path:path>', map_redirect)
    )

document/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Document(models.Model):
    CATEG_CHOICES = (
        ('anleit', "KSP Anleitungen"),
        ('wanleit', "Weitere Anleitungen"),
        ('wepana', "WEP Analyseteile"),
    )
    doc = models.FileField(upload_to='documents', verbose_name=_("File"))
    title = models.CharField(max_length=255, verbose_name=_("Title"))
    date = models.DateField(_("Date"))
    category = models.CharField(max_length=10, choices=CATEG_CHOICES, default='anleit')
    published = models.BooleanField(default=True)
    weight = models.SmallIntegerField(default=0)

    @property
    def fformat(self):
        return self.doc.path.rsplit('.')[-1]

templates/anzahl_pro_gemein.html
{% extends "base.html" %}
{% load ksp_utils %}

{% block content %}
<h2>Anzahl Stichproben pro Gemeinde und Aufnahmejahr</h2>

<table class="numbers">
<thead><tr><th>Gemeinde</th><th>Jahr</th><th>Anzahl</th></tr></thead>
<tbody>
{% for res in result %}
  <tr><td>{{ res.0|gem_name }}</td><td>{{ res.1 }}</td><td>{{ res.2 }}</td></tr>
{% endfor %}
</tbody></table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
  <title>KSP {% block htitle %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <script>
    var static_url = "{{ STATIC_URL }}";
  </script>
  <link rel="stylesheet" href="{% static 'css/themes/smoothness/jquery-ui.css' %}">
  <script src="{% static 'js/jquery-1.12.0.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.min.js' %}"></script>
  <script src="{% static 'js/global.js' %}"></script>
  {% block extra_head %}{% endblock %}
</head>

<body>
  <div id="global">
    <div id="header">
        <div id="header_bar">
          <div id="logo">
            <img src="{% static 'img/logoafw.jpg' %}">
          </div>
        <ul id="main_menu">
            <li>{% if not on_home %}<a href="{% url 'home' %}" title="zurück zur Übersicht">{% endif %}
        Home{% if not on_home %}</a>{% endif %}</li>
            <li><a href="{% url 'data_page' %}">Datenanforderungen</a></li>
            <li><a href="{% url 'docs' %}">Dokumentation</a></li>
         </ul>
        </div>
    </div>

    <div id="main">
        {% if user.is_authenticated %}
          <div id="loggedin">Angemeldet als {{ user.username }} - <a href="{% url 'logout' %}">ausloggen</a></div>
        {% endif %}

        <div id="page-title">{% block title %}<h1>Plattform der Kontrollstichprobenaufnahmen in den beiden Basel</h1>{% endblock %}</div>

      <div style="clear: both;"></div>

      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|linebreaksbr }}</li>
        {% endfor %}
      </ul>
      {% endif %}
      
      <div class="content">
      <div id="dialog-div" style="display: none;" title="Informationen"></div>
      {% block content %}
      {% endblock %}
      </div>
    </div>
    <div id="footer">
      Internetseite: <a href="http://www.guaraci.ch">Guaraci</a> &amp; <a href="http://www.2xlibre.net">2xlibre.net</a>
    </div>
  </div>
</body>
</html>

templates/data_grid.html
{% load ksp_utils %}
{% if error %}<div class="error">{{ error }}</div>
{% else %}
  <div style="margin: 0.5em 0"><b>{{ perimeter_feedback.0 }}:</b> {{ perimeter_feedback.1 }}</div>
  {% if total %}<div style="font-size:x-small; font-style: italic">Linien: {{ total }}</div>{% endif %}

<table id="data_grid" class="numbers tablesorter">
  <thead>
  <tr>{% for th_line in field_names|ordered_heads:ordering %}
        {{ th_line }}
      {% endfor %}
  </tr>
  </thead>
  <tbody>
  {% for line in query %}
    <tr>
    {% for td_line in line|ordered_vals:ordering %}
        {{ td_line }}
    {% endfor %}
    </tr>
  {% empty %}
    <tr><td colspan="5">Leider ergab Ihre Suchanfrage keinen Daten</td></tr>
  {% endfor %}
  </tbody>
</table>
<div class="db_view">[aus <a href="{% url 'view_def' db_view.oid %}">{{ db_view.name }}</a>]</div>
{% endif %}

templates/docs.html
{% extends "base.html" %}

{% block htitle %}Dokumentation{% endblock %}

{% block content %}
<h2>Dokumente</h2>
<ul>
{% for doc in docs %}
    {% ifchanged doc.category %}<h3>{{ doc.get_category_display }}</h3>{% endifchanged %}
    <li><a href="{{ doc.doc.url }}">{{ doc.title }}</a> <small>({{ doc.fformat }}, {{ doc.date }})</small></li>
{% endfor %}
</ul>

<h2>Datenbankdokumentation</h2>
<ul>
    <li><a href="https://gitlab.com/guaraci/ksp/blob/master/docs/KSP-DBSchema.pdf">Datenbankschema (pdf)</a></li>
    <li><a href="{% url 'view-list' %}">Liste der Datenbank "views"</a></li>
    <li><a href="{% url 'table-list' %}">Liste der Datenbank Tabellen</a></li>
</ul>

<h2>Glossare</h2>

<p><b>Erklärung der Begriffe der forstlichen Planung:</b> <a href="{% url 'glossar' %}">Glossar</a></p>

<h3>Definitionen zur Auswertung des Kontrollstichproben</h3>
<p><i>Siehe auch:</i>
    <ul>
    <li><i><a href="http://www.lfi.ch/glossar/glossar.php">LFI Definitionen</a></i></li>
    </ul>
</p>
<dl>
    <a name="einwuchs"></a><dt>Einwuchs</dt>
    <dd>Gesamtheit der Stammzahl oder des Volumens jener Bäume, deren Brusthöhendurchmesser zwischen zwei aufeinander folgenden Inventuren die Kluppierungsschwelle überschritten hat. Alle Probebäume welche neu eingewachsen sind (tree_obs.vita_id = 3). Der Einwuchs kann erst für ein Folge-Inventar berechnet werden.</dd>

    <a name="lebender-zuwachs"></a><dt>Lebender Zuwachs</dt>
    <dd>Der jährliche Volumen-Zuwachs aller lebenden Bäume zwischen zwei aufeinander folgenden Inventuren (tree_obs.vita_id = 2) - laufender jährliche Zuwachs aller lebenden Bäume. Das Volumen des Einwuchs wird addiert.</dd>

    <a name="lokale-dichte"></a><dt>Lokale Dichte</dt>
    <dd>Siehe <a href="{% url 'func_def' 'ksp_lokale_dichte' %}">Datenbank Definition</a>.</dd>
    </dd>

    <a name="nutzung"></a><dt>Nutzung</dt>
    <dd>Entnahme von Holz und Bäumen (durch waldbauliche Eingriffe) oder von anderen Waldressourcen (z.B. Harz, Samen). Alle Bäume (sind nicht Probebäume) welche seit der letzten Aufnahme genutzt wurden (tree_obs.vita_id = 1). Die Nutzung kann erst für ein Folge-Inventar berechnet werden.</dd>

    <a name="probebaume"></a><dt>Probebäume</dt>
    <dd>Baum, der Bestandteil der Stichprobe einer Inventur ist. Baum der auf einer Probefläche des Forstinventars des Amt für Wald beider Basel steht, einen Durchmesser grösser oder gleich der Kluppierschwelle (tree_obs.dbh = 12cm) hat sowie die Aufnahmeart = Kontrollstichprobe (tree_obs.survey_type_id=1) aufweist. Ein Probebaum ist lebend (tree_obs.vita_id = 2) oder neu eingewachsen (tree_obs.vita_id = 3).<br>
    Bemerkung: Grundsätzlich gibt es keine Bäume mit tree_obs.vita_id = 2 oder tree_obs.vita_id = 3 welche einen BHD (tree_obs.dbh) kleiner als 12 cm haben.</dd>

    <a name="probeflache-gultig"></a><dt>Probefläche gültig</dt>
    <dd>Zufällig oder systematisch ausgewählter Teil der Waldfläche, auf der die Baum-, Bestandes- und Flächenmerkmale erhoben werden. Die Probeflächen des Forstinventars des Amt für Wald beider Basel besteht aus einem konzentrischen Kreis von 3 Aren Horizontalfläche. Der Radius einer Probefläche bis 20% Neigung beträgt 9.77 Meter. Anschliessend wird der Radius der Probefläche gemäss der folgenden Tabelle korrigiert (Link Übersichtstabelle Flächenkorrektur auf Grund der Hangneigung). Der Waldrandfaktor (plot_obs.forest_edgef) liegt zwischen 0.6 und 1.0.</dd>

    <a name="standardabweichung"></a><dt>Standardabweichung</dt>
    <dd>Quadratwurzel aus dem Durchschnitt der quadrierten Abweichungen von Einzelwerten zu ihrem Mittelwert. Sie dient als Mass für die Streuung der untersuchten Grundgesamtheit.</dd>

    <a name="stichprobennetz"></a><dt>Stichprobennetz</dt>
    <dd>Das Stichprobennetz ist ein Gitternetz, welches die gesamte Kantonsfläche abdeckt. Das Gitternetz weist je nach Inventur eine unterschiedliche Maschenweite auf. Auf den Schnittpunkten des Netzes, die auf Grund des Waldentscheides im Luftbild wahrscheinlich Wald sind, liegen die terrestrischen Proben der kantonalen Inventur.</dd>

    <a name="tote-baume"></a><dt>Tote Bäume</dt>
    <dd>...werden nur zur Totholzberechnung berücksichtigt. Ein Totholzbaum ist seit der letzten Aufnahme abgestorben (tree_obs.vita_id = 4)</dd>

    <a name="totholz"></a><dt>Totholz</dt>
    <dd>Abgestorbenes Holz (Bäume, Äste, Strünke). Es wird oft zwischen stehendem und liegendem Totholz unterschieden. Totholz ist ein wichtiges Biotop für viele Tier- und Pflanzenarten sowie Pilze.<br>
    siehe auch <a href="https://www.baselland.ch/fileadmin/baselland/files/docs/vsd/forstamt/doku/totholz_charta.pdf">Totholz-Charta BL/BS</a></dd>

    <a name="vorrat"></a><dt>Vorrat (Holzvorrat)</dt>
    <dd>Schaftholzvolumen in Rinde der lebenden Bäume und Sträucher (stehende und liegende) mit erkennbarer Gehölzart ab 12 cm BHD (tree_obs.vita_id = 2 OR tree_obs.vita_id = 3) AND tree_obs.dbh > 11)</dd>

    <a name="waldboden"></a><dt>Waldboden (bestock und unbestockt)</dt>
    <dd>Der Wert Blösse (plot_obs.gap_id) hat keinen Einfluss auf die Definition der Probefläche. Eine Blösse bezeichnet nicht bestockten Waldboden (z.B. Waldstrasse). Der Unterschied von Blösse und nicht Holzboden ist nicht klar.</dd>

</dl>

<hr>

{% if backups %}
<h2>Sicherungen</h2>
<em>Nur sichtbar für 'Staff' Benutzer</em>
<ul>
  {% for file in backups %}
    <li><a href="{% url 'serve-backup' file.name %}">{{ file.name }}</a></li>
  {% endfor %}
</ul>
{% endif %}

{% endblock %}

templates/gemeinden.html
{% extends "base.html" %}
{% load ksp_utils %}

{% block extra_head %}
<script>
    $(document).ready(function () {
        color_standardfehler($("td.sf"));
    });
</script>
{% endblock %}

{% block content %}
<div style="float:right;">
    {{ inv_choice|safe }}
</div>
<br clear="right">

<table class="numbers" style="margin: 0 auto;">
<thead><tr>
    <th>Gemeinde <div class="icons"><img class="info" src="{{ STATIC_URL }}img/info.png" title="politische Gemeinde"></div></th>
    <th>Waldfläche (2015)
        <div class="icons"><img class="info" src="{{ STATIC_URL }}img/info.png" title="Die theoretische Waldfläche basiert auf der Auswertung der Bestandeskarte 2015">
        </div>
    </th>

    <th>Jahr <div class="icons"><img class="info" src="{{ STATIC_URL }}img/info.png" title="Aufnahmejahr der Kontrollstichproben"></div></th>
    <th>Anzahl<br>Probepunkte
        <div class="icons"><img class="info" src="{{ STATIC_URL }}img/info.png" title="Anzahl der aufgenommen Probepunkte">
        </div>
    </th>
    <th>Anzahl<br><a href="{% url 'docs' %}#probebaume">Probebäume</a></th>
    <th>theoretische Waldfläche
        <div class="icons"><img class="info" src="{{ STATIC_URL }}img/info.png" title="Gesamtheit aller Flächen, die gemäss Walddefinition der Aufnahmeleitung als Wald bezeichnet werden und durch Kontrollstichprobenflächen repräsentiert sind. Unbestockte Flächen oder Waldstrassen (Blösen) gehören ebenfalls zur Waldfläche.">
        </div>
    </th>

    <th>Stammzahl (Stk./ha)
        <div class="icons">
          <img class="info" src="{% static 'img/info-blue.svg' %}"
            title="{{ descriptions.stammzahl.short }} Klicken Sie für weitere Informationen."
            data-url="{% url 'doc-specific' 'stammzahl' %}">
        </div>
    </th>
    <th title="Standardfehler">Sf [%]</th>

    <th>Vorrat Einheitstarif BL (m<sup>3</sup>/ha)
        <div class="icons">
          <img class="info" src="{% static 'img/info-blue.svg' %}"
            title="{{ descriptions.volumen.short }} Klicken Sie für weitere Informationen."
            data-url="{% url 'doc-specific' 'volumen' %}">
        </div>
    </th>
    <th title="Standardfehler">Sf [%]</th>

    <th>Grundfläche (m<sup>2</sup>/ha)
        <div class="icons">
          <img class="info" src="{% static 'img/info-blue.svg' %}"
            title="{{ descriptions.grundflache.short }} Klicken Sie für weitere Informationen."
            data-url="{% url 'doc-specific' 'grundflache' %}">
        </div>
    </th>
    <th title="Standardfehler">Sf [%]</th>
    </tr>
</thead>
<tbody>
{% for name, gem in gemeinden.items %}
  {% if not gem.years %}
    <tr><td valign="top"><a href="{% url 'gemeinde' gem.obj.pk %}">{{ gem.obj.name_with_k }}</a></td>
        <td>-</td><td>-</td><td>-</td>
    </tr>
  {% else %}
    {% for data in gem.years %}
    <tr>{% if forloop.first %}
        <td valign="top" rowspan="{{ gem.years|length }}">
            <a href="{% url 'gemeinde' gem.obj.pk %}">{{ gem.obj.name_with_k }}</a>
        </td>
        <td valign="top" rowspan="{{ gem.years|length }}">
            {{ data.waldflaeche_bestand|div:10000|floatformat }}
        </td>
        {% endif %}
        <td>{{ data.jahr|default_if_none:'-' }}</td>
        <td>{{ data.probepunkte }}</td><td>{{ data.probebaum_abs|default_if_none:'-' }}</td>
        <td>{{ data.waldflaeche|default_if_none:'-' }}</td>
        <td>{{ data.stammzahl_ha|default_if_none:'-' }}</td><td class="sf">{{ data.stammzahl_stdf|display_value }}</td>
        <td>{{ data.volumen_ha|default_if_none:'-' }}</td><td class="sf">{{ data.volumen_stdf|display_value }}</td>
        <td>{{ data.grundflaeche_ha|default_if_none:'-' }}</td><td class="sf">{{ data.grundflaeche_stdf|display_value }}</td>
    </tr>
    {% endfor %}
  {% endif %}
{% endfor %}
</tbody></table>
<div class="db_view">[aus <a href="{% url 'view_def' db_view.oid %}">{{ db_view.name }}</a>]</div>

<div class="icons">
    <a href="?format=csv" class="icon"><img src="{{ STATIC_URL }}img/csv.png" alt="CSV logo" title="Export als CSV"></a>
</div>

<div style="margin-top: 1em; font-size: small; color: #444;">
    <div style="display: inline-block; height: 1.4em; width: 3em; background-color: #fabf8f"></div>
    Standardfehler über 10%<br>
    <div style="display: inline-block; height: 1.4em; width: 3em; background-color: #ff6161"></div>
    Standardfehler über 25%
</div>

{% endblock %}

templates/inventory_detail.html
{% extends "base.html" %}
{% load ksp_utils %}

{% block htitle %}{{ inventory.municipality.name }} - {{ inventory.year }}{% endblock %}

{% block extra_head %}
{% include "map_headers.html" %}
  <script src="{% static 'js/inventory.js' %}"></script>

<style>
div#map { display: inline-block; text-align: center; width: 60%; max-width: 800px; height: 500px; margin-bottom: 0.5em; }
div#legend { display: inline-block; width: 37%; font-size: small; }
form#newplot_form, form#shapeForm { display: none; }
input#id_latitude, input#id_longitude { padding: 5px 0; }
fieldset#plot-details { margin-bottom: 1em; }
fieldset#plot-details legend { font-size: large; font-weight: bold; }
</style>

<script>
var gem_vector = JSON.parse('{{ inventory.municipality.as_geojson|safe }}'),
    municipalityCenter = {{ center|coords_to_js }},
    inventory = {
        is_passed: {{ inventory.is_passed|yesno:'true,false' }},
        plotobs_url: "{% url 'inventory-plotobs' inventory.pk %}",
        plots_noobs_url: "{% url 'inventory-plots-no-obs' inventory.pk %}",
        exclude_plots_url: "{% url 'inventory-exclude-plots' inventory.pk %}"
    };
</script>
{% endblock %}

{% block content %}
<h1>Inventar {{ inventory.municipality.name }} - {{ inventory.year }}</h1>

<div id="map"></div>
<div id="legend">
    <div><img src="{% static 'img/poly_gem.png' %}" width="20"> Gemeindepolygon</div>
    <div><img src="{% static 'img/poly_inv.png' %}" width="20"> Inventarpolygon</div>
    <div><img src="{% static 'img/point_blue.png' %}"> Dieser Plot wurde inventarisiert (<span id="plotobsCount"></span>).</div>
    <div><img src="{% static 'img/point_white.png' %}"> Dieser Plot wird nächstens inventarisiert (war in letztes Inventar) (<span id="plotCurrentCount"></span>).</div>
    <div><img src="{% static 'img/point_lgrey.png' %}"> Dieser Plot wird nächstens inventarisiert (war <b>nicht</b> in letztes Inventar) (<span id="plotObsoleteCount"></span>).</div>
    <div><img src="{% static 'img/point_grey.png' %}"> Dieser Plot wird <b>nicht</b> inventarisiert (<span id="plotExcludedCount"></span>).</div>
</div>
<div id="plot"></div>

{% if not inventory.is_passed %}
<div id="newplot">
    <button id="showform">KSP hinzufügen</button>
    <!--button id="savePolygon" data-url="{% url 'inventory-savepolygon' inventory.pk %}">Inventar Polygon speichern</button-->
    <button id="shpBtn">KSP aus Shapefile importieren</button>

    <form id="newplot_form" action="{% url 'inventory-new-plot' inventory.pk %}" method="post">
        {% csrf_token %}
        Länge: <input id="id_longitude" name="longitude" type="number" step="100"><br>
        Breite: <input id="id_latitude" name="latitude" type="number" step="100"><br>
        <button id="newplot_submit">Speichern</button>
        <button id="newplot_cancel">Stornieren</button>
    </form>

    <form id="shapeForm" action="{% url 'inventory-new-plots-shape' inventory.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
        <h3>Shapefile (.zip) importieren</h3>
        <input type="file" name="shapefile"><br>
        <button id="shapeForm_submit">Importieren</button>
        <button class="cancel">Stornieren</button>
        </fieldset>
    </form>
</div>
{% endif %}

<script>


</script>
{% endblock %}

templates/map_headers.html
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/ol3/4.2.0/ol.css" type="text/css">

<script src="//cdnjs.cloudflare.com/ajax/libs/proj4js/2.2.1/proj4.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ol3/4.2.0/ol.js"></script>

<script src="{{ STATIC_URL }}js/map.js"></script>

templates/model_data.html
{% extends "base.html" %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/highlight.default.min.css' %}">
<script src="{% static 'js/jquery.tablesorter.min.js' %}"></script>
<script src="{% static 'js/highlight.min.js' %}"></script>
<script>
    $(document).ready(function() {
        $("table.tablesorter").tablesorter({
            sortList: [[0,0]]
        });
    });
</script>
<script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

{% block content %}
<h2>{{ title }}</h2>
{% if comment %}{{ comment }}{% endif %}
<pre><code>{{ definition|safe }}</code></pre>

<i>{{ data.count }} Zeilen:</i>
<table id="data_grid" class="numbers tablesorter">
  <thead>
      <tr>{% for name in field_names %}<th>{{ name }}</th>{% endfor %}</tr>
  </thead>
  <tbody>
      {% for line in data %}<tr>{% for item in line %}<td>{{ item }}</td>{% endfor %}</tr>{% endfor %}
  </tbody>
</table>
{% endblock %}

templates/plots_to_check.html
{% extends "base.html" %}

{% block content %}
<h1>Plots to check</h1>
<ul>
{% for plot in plots %}
  <li><a href="{{ plot.get_absolute_url }}">{{ plot }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/tree_edit.html
{% csrf_token %}
{{ form.as_p }}
<input id="ok" type="submit" value="OK">
<input id="cancel" type="button" value="Abbrechen">